defaults:
  - default  # Inherits from configs/order_agent/default.yaml
  - override prompts: always_cancel_prompt  # Uses the always_cancel_prompt.yaml

# This file inherits all the settings from configs/order_agent/default.yaml
# and only overrides the prompts to use the always_cancel_prompt
