# configs/customer_agent/urgent_canceller_agent.yaml

defaults:
  - _self_
  - /llm: openai_gpt4_temp
  - prompts: urgent_canceller_prompts

customer_agent:
  mock_api_base_url: "http://localhost:8001"
  customer_name: "Urgent Pat Canceller"
  order_id: null
  min_turns_per_conversation: 3
  max_turns_per_conversation: 7

